name: Release

on:
  push:
    branches:
      - main

jobs:
  versioning:
    name: Versioning
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Release Please
        uses: google-github-actions/release-please-action@v2
        with:
          release-type: node
        id: release-please
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
